### ISSUE TITLE
Consider allowing microbenchmarks to be disabled

### ISSUE THREAD

**Issue by ldionne** [ldionne/metabench#119]
I encountered a case where the microbenchmark thing actually caused the gathered data to be nonsense. The problematic benchmark is in [this](https://gist.github.com/ldionne/feddaf8f0530cb36bab84026215df9e4) Gist. In that benchmark, I use a slightly modified version of Metabench which does not subtract the base time of the compilation, because otherwise the curves are nonsense. Either there's something I don't understand about that benchmark, or there's something fishy with our implementation of microbenchmarks and it might be wise to allow switching it off to simply measure a whole file.

**Comment by ldionne** [comment]
It just occurred to me that instead of removing the baseline in the Ruby script, we could provide both measurements to the Javascript and we could then do the calculation there instead. Each chart could then provide the ability to show either with or without the baseline, or something like that.

In a similar vein, we could perhaps forward _all_ data points to the Javascript and apply any filters there. This would give us the flexibility to show error bars and stuff like that. I don't think we need this for now, but this is something to keep in mind.

**Comment by brunocodutra** [comment]
Great idea!

**Comment by ldionne** [comment]
This is obsoleted by #155, which makes it possible to turn microbenchmarks on/off per graph.
