### ISSUE TITLE
Associate fixed curve colours to libraries

### ISSUE THREAD

**Issue by ldionne** [ldionne/metabench#127]
Right now, curve colours are assigned to libraries as the JS plotting library desires. This can be confusing then viewing multiple graphs. Instead, it would be better if each library was assigned a fixed colour.

**Comment by brunocodutra** [comment]
It [looks like](http://nvd3.org/examples/line.html) this is just a matter of adding a further property to the dataset JSON called `color`.

@ldionne @ericniebler @edouarda what colour do you want benchmarks for your libraries to be?

**Comment by edouarda** [comment]
I will take the most expensive one.

**Comment by ldionne** [comment]
No strong preference.

**Comment by brunocodutra** [comment]
Alright, so I chose colours roughly in alphabetical order out of [this color pallette](http://colorbrewer2.org/#type=qualitative&scheme=Set1&n=5) and opened a PR.

I suggest this issue be closed and the discussion moved to #142.
