### ISSUE TITLE
Install Clang from LLVM APT sources?

### ISSUE THREAD

**Issue by brunocodutra** [ldionne/metabench#130]
LLVM APT sources are back up and running and provide up to Clang 3.9 (which we still don't benchmark btw), so wouldn't it be better to rely on Travis addons feature to install Clang?

The only drawback I see with this approach is the fact libc++ doesn't seem to be provided for precise, so we might still have to compile it manually if we really can't live with Clang using  libstdc++.

**Comment by ldionne** [comment]
I think there's no such thing as Clang 3.9. I think there's Clang 3.8.1 and Clang trunk, which will turn into Clang 4.0.0. Do we want to benchmark on trunk compilers?

**Comment by brunocodutra** [comment]
I'm pretty sure there is such a thing as Clang 3.9:
https://travis-ci.org/brunocodutra/metal/jobs/148736501#L405

**Comment by brunocodutra** [comment]
The relevant .travis.yml is [here](https://github.com/brunocodutra/metal/blob/master/.travis.yml#L83).
