### ISSUE TITLE
missing brigand support on several algorithms

### ISSUE THREAD

**Issue by porkybrain** [ldionne/metabench#134]
partition and "fold right" are missing for brigand. (fold right is called 'reverse_fold' in brigand)

**Comment by porkybrain** [comment]
partition is also missing for meta

**Comment by ldionne** [comment]
I'll be thrilled to merge a PR that adds them :-)

**Comment by brunocodutra** [comment]
while you are at it, consider adding `sort`, `any`, `all` and `distinct` c-:

**Comment by ldionne** [comment]
Regarding `sort`, I've got a WIP patch that adds it. See [this](https://github.com/ldionne/metabench/commit/0d1421549ead41eeaeff8db4c61f4e5072d1b8ce). You can let me add this one.

**Comment by brunocodutra** [comment]
> Regarding sort, I've got a WIP patch that adds it. See this. You can let me add this one.

Looks great. Is there a way to make sure the exact same random numbers will be generated for all benchmarks in the same set? Maybe seed it using the current calendar day (let's just forget about the possibility of nightly.es triggering the build around midnight).

**Comment by ldionne** [comment]
I already seed the generator with `0` in all the tests.

**Comment by porkybrain** [comment]
I'm looking forward to sort ;) I will make a pull request as soon as I find time.

**Comment by brunocodutra** [comment]
> I already seed the generator with 0 in all the tests

Oh I see, forgive my ruby illiteracy

**Comment by porkybrain** [comment]
#135 is the PR

**Comment by ldionne** [comment]
Closing in favor of #135.
