### ISSUE TITLE
Add mp11 support

### ISSUE THREAD

**Issue by odinthenerd** [ldionne/metabench#136]
How hard would it be to add support for [MP11](https://github.com/pdimov/mp11)? Because of the approach to lambdas mp11 should be fastest in most cases, it would be nice to see how close we are to the "baseline" with our fancier lambda strategies.

**Comment by brunocodutra** [comment]
> How hard would it be to add support for MP11? 

I don't think it would be hard at all, just laborious.
If you want to give it a shot I'll be glad to review.

**Comment by odinthenerd** [comment]
I think the "fast part" of mp11 is in kvasir now, not sure if this is really interesting any more

**Comment by ldionne** [comment]
Ok, let's close this.

**Comment by odinthenerd** [comment]
how funny, the day we close this issue is the day mp11 requests formal boost review. Suddenly this is relevant again.

**Comment by odinthenerd** [comment]
added an issue in mp11, probably better there than here https://github.com/pdimov/mp11/issues/3

**Comment by ldionne** [comment]
I'll let him open a PR if he wants in.

**Comment by odinthenerd** [comment]
I'm making one for him, should have it done tomorrow
