### ISSUE TITLE
Travis time limit blown up

### ISSUE THREAD

**Issue by brunocodutra** [ldionne/metabench#145]
After the recent inclusion of new algorithms some builds have been [blowing up Travis time limit](https://travis-ci.org/ldionne/metabench/jobs/154068674).

**Comment by brunocodutra** [comment]
A quick fix would be to set `MEDIAN_OF` to `1`, another one would be to lower the maximum size of lists to at most `~100` and/or reduce the number of samples.

**Comment by ldionne** [comment]
In fact, I've been having trouble with GCC timing out for a while, even before those changes. Changing `MEDIAN_OF` to `1` seems like a bad idea, since we implemented this precisely to make the timings more accurate. I guess what we could do is reduce the size of lists to at most `100` on GCC only?

**Comment by brunocodutra** [comment]
> Changing `MEDIAN_OF` to `1` seems like a bad idea, since we implemented this precisely to make the timings more accurate

While I agree with this in theory, the prevalence of negative timings in practice make me wonder whether `MEDIAN_OF 3` is indeed improving things that much to justify builds taking three times longer to run.

>  I guess what we could do is reduce the size of lists to at most 100 on GCC only?

TBH I'd rather lower the limit for every compiler equaly, because the way the benchmark module is setup today doesn't make it feasible to have ranges depend on compilers without a major refactoring. Plus we will probably start having problems with other compilers once we add missing benchmark cases anyways.

**Comment by porkybrain** [comment]
seems like the mpl.list and mpl.vector are taking up a lot of the time, on the other hand those algorithms are not changing. Maybe we should just use fixed values for them rather than recalculating them every time.

**Comment by brunocodutra** [comment]
> Maybe we should just use fixed values for them rather than recalculating them every time.

I don't think this is a good idea, because what if it changes due to external factors such as an update of Travis' virtual images? That said, you called my attention to the fact cloning the entire boost from GitHub is what takes the longest even though it is only necessary in order to provide MPL and Fusion benchmarks, which you well noted shouldn't change too often due to updates upstream. That means we could do just as well by downloading the latest compressed package, which should be much faster than cloning a bunch of individual git repositories. 

It should be very easy to get the URL for the latest release by greping sourceforge. They even have [snapshot releases](https://sourceforge.net/projects/boost/files/boost/snapshots/master/) from the branch master, so we won't even lag too much behind the head. I'll give it a shot as soon as I find time.

**Comment by brunocodutra** [comment]
Didn't think it would be that easy, but sourceforge already provides a fixed URL to the latest release of boost: `https://sourceforge.net/projects/boost/files/latest/download`. It won't get us the latest snapshot, but we should do just fine with the latest stable release.

oh well, no fun with grep anymore :-c

**Comment by porkybrain** [comment]
cool, come to think of it I noticed that boost took forever but was not smart enough to put 2 and 2 together.

**Comment by porkybrain** [comment]
by the way how long does it take for the results to show up? brigand::filter has been in for a while and is still not showing, did I maybe screw it up or something?

**Comment by brunocodutra** [comment]
overnight usually, check the chart's footer for the timestamp of the latest update for a given <algorithm x compiler> pair.

**Comment by brunocodutra** [comment]
Quoting myself from [another thread](https://github.com/ldionne/metabench/pull/146#issuecomment-241944773)

> Personally I suspect the root cause of this issue lies on the fact something is suboptimal in our setup so that we are somehow wasting valuable resources for meager gains. Personally I think the median filter is to blame here and I was originally planing to investigate an alternative which could deliver similar results but that wouldn't cost that much timewise

So I've been experimenting with low-pass filtering data in an effort to get rid of noise and it seems to deliver similar results to taking the median of several runs for a given sample, yet at a third of the cost timewise. 

It would be basically just a simple mean filter, i.e. such that `f(i) = (f(i) + f(i + 1))/2`, what do you guys think? I'll try to get you some examples later.

**Comment by ldionne** [comment]
I think this makes sense for small sequence sizes, but not for large sequence sizes where `f(i)` and `f(i+1)` have a large difference?

**Comment by ldionne** [comment]
Also, FWIW, turning off the median of 3 significantly decreases the Travis time: https://travis-ci.org/ldionne/metabench/builds/154668593

**Comment by brunocodutra** [comment]
> I think this makes sense for small sequence sizes, but not for large sequence sizes where f(i) and f(i+1) have a large difference?

Where the steps in the `x` axis are larger we have a lower sample rate, so the actual absolute value for the cutoff frequency of the mean filter decreases, but its relative value with respect to the sample rate remains constant. That is, it doesn't make things any worse than they already are due to the low sample rate, while we still suppress higher frequencies which are due to noise. BTW if the mean filter proves effective, we could afford to increase the number of samples a little and still be much faster than using `MEDIAN_OF`.

**Comment by porkybrain** [comment]
when using fast tracks an algorithms efficiency could actually be a saw tooth.

**Comment by brunocodutra** [comment]
Indeed, but only if the sample rate is very high. Basically it is so low
for the benchmark suite that this is likely to not be observable at all.
Technically it could even screw results up due to aliasing (nyquist's
theorem), but I don't believe the effects are significant. Do you have any
concrete example of this theoretical saw tooth or of aliasing caused by
fast tracking?

**Comment by porkybrain** [comment]
brigand at should be a saw tooth

**Comment by brunocodutra** [comment]
Have you observed this in practice using metabench?

**Comment by porkybrain** [comment]
no, the granularity is too course, the period of the saw tooth should be 16 elements

**Comment by brunocodutra** [comment]
That's what I was trying yo say with all that babbling about sample rate &
friends. For the purpose of suppressing noise here, a coarse low pass
filter should work just fine with no loss to data we already don't observe
anyways.

**Comment by ldionne** [comment]
I think trying the low pass filter that you propose would be worthwhile. You said you had experimented with it; are there any results we could see at this point?

**Comment by brunocodutra** [comment]
I was experimenting with raw data on Octave. I'll try to post some results
here once I can find some time.

**Comment by brunocodutra** [comment]
Does filtering data even make sense anymore since #149?
