### ISSUE TITLE
Benchmarks stopped updating

### ISSUE THREAD

**Issue by brunocodutra** [ldionne/metabench#159]
Any clue why results were `Last updated on Thu, 10 Nov 2016`?

**Comment by ldionne** [comment]
Oh, yeah I know. I'm going to fix it. I got the same problem with Hana.

**Comment by ldionne** [comment]
Should be fixed by cdc2553.

**Comment by ldionne** [comment]
Yes, this is now fixed (the benchmarks for GCC are still outdated but that's because they timeout, and that's a separate problem).
