### ISSUE TITLE
Add testing on MSVC

### ISSUE THREAD

**Issue by ldionne** [ldionne/metabench#18]
Right now, Appveyor only tests on Clang-cl. We should also test on MSVC.

**Comment by ldionne** [comment]
Preliminary trials suggest that this is just a matter of setting `CMAKE_CXX_COMPILER=cl` instead of `clang-cl`.

**Comment by brunocodutra** [comment]
Would it make any difference to use other versions of MSVC, I mean, does it depend on the compiler at all or just on the generator?

Also, shouldn't we explicitly test NMake and NMake JOM to make sure it works with both of them?

**Comment by ldionne** [comment]
I'm pretty sure it should work with any version of MSVC, provided they can compile the example benchmarks (which need C++11). And yes, we should probably test the other generators to make sure they work, but I've no experience with them. Have you used these NMake generators?

**Comment by brunocodutra** [comment]
Not like this no, but leave this on me, I'll figure it out later today.

**Comment by ldionne** [comment]
Ok, awesome. Just create a PR whenever you're ready.

**Comment by brunocodutra** [comment]
Ok, will do.

**Comment by brunocodutra** [comment]
Almost got it working for "Ninja", "NMake Makefiles", "Unix Makefiles" and "MSYS Makefiles", however:

* NMake hangs while compiling (progress bar never increases)
* Unix Makefiles produce the following error which I believe is related to Ruby

> Scanning dependencies of target path.to.benchmark
> [ 50%] Generating path/to/benchmark.json
> -e:2: unknown regexp options - tabch 
> CMakeFiles/path.to.benchmark.dir/build.make:64: recipe for target 'path/to/benchmark.json' failed

Any ideas?

**Comment by brunocodutra** [comment]
...never mind Unix Makefiles, got it finally working by double quoting ruby commands.

**Comment by brunocodutra** [comment]
...and out of the sudden NMake started working as well.

Alright, I'll squash it all to a single commit and open a PR later today.

**Comment by ldionne** [comment]
Did you rebase your work on top of master? There was an error related to `-e:2: unknown regexp options - tabch ` when I worked on the initial support for Appveyor, but it's been fixed now.

**Comment by brunocodutra** [comment]
I think so. I suppose that's when you double quoted one of the commands? I just did the same for all of them and everything started working.
