### ISSUE TITLE
Benchmark on Clang 4.0, Clang 5.0 and GCC 7.1

### ISSUE THREAD

**Issue by brunocodutra** [ldionne/metabench#182]
It should be possible to benchmark these compilers if we move to Trusty, [which provides container based infrastructure now](https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments), i.e., `sudo: false`.

**Comment by brunocodutra** [comment]
This has been demonstrated by @pdimov [here](https://github.com/pdimov/mp11/blob/develop/.travis.yml#L120)

**Comment by pdimov** [comment]
clang-4 from llvm-toolchain-trusty-4.0 even works on precise:

https://github.com/pdimov/mp11/blob/develop/.travis.yml#L253

**Comment by ldionne** [comment]
@brunocodutra Do you know in what apt-sources Clang 5.0 is located? I see it's a whitelisted package, but I don't see a corresponding apt source.

**Comment by ldionne** [comment]
This is addressed by #185, except for Clang 5.0 which I don't know where it's at.

**Comment by brunocodutra** [comment]
AFAIK Clang trunk is provided by `llvm-toolchain-trusty`, but in case that doesn't work, for some reason that I can't seem to recall [here's what I use on my projects instead](https://github.com/brunocodutra/metal/blob/master/.travis.yml#L232).

**Comment by ldionne** [comment]
Ooh, I did not realize Clang 5 was trunk. I'd rather not add trunk since its apt-source will change from time to time and that means more maintenance. Do you think it's very important to have it?

**Comment by brunocodutra** [comment]
Do you think it's very important to have it?


Not really, we should be fine :)

Thanks for looking into this!

**Comment by ldionne** [comment]
Ok, closing as this was addressed in #185. We'll add Clang 5.0 when it's not trunk anymore.
