### ISSUE TITLE
mp11 breaks the benchmarks

### ISSUE THREAD

**Issue by ldionne** [ldionne/metabench#188]
See https://travis-ci.org/ldionne/metabench/builds/273563691

@pdimov, can you please have a look? If we can't resolve the issues, I'm going to have to disable mp11 from Metabench until it's fixed.

**Comment by pdimov** [comment]
These run against boost-1.64.0, I assume? config/workaround.hpp is new for 1.65.0. Could we up the Boost release, or would I need to revert the mp11 commit?

**Comment by ldionne** [comment]
Thanks for the diagnostic. I'm running [a build](https://travis-ci.org/ldionne/metabench/builds/273691023) with 1.65, and I'll update it on `master` if the build succeeds. Note that for some reason, all of my Travis repositories are broken or hanging right now (no idea why), so this may take a while to get through.

**Comment by pdimov** [comment]
Travis macOS was stopped due to issues and accumulated an enormous backlog, see https://www.traviscistatus.com/

So all jobs that have a macOS entry were blocked.

**Comment by pdimov** [comment]
I decided to revert mp11 to not use config/workaround.hpp, to remain usable with 1.64.

**Comment by ldionne** [comment]
Okay. FWIW, I still updated to Boost 1.65 just now.
