### ISSUE TITLE
`render': undefined method `times' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by cppljevans** [ldionne/metabench#189]
Followed template here:

  https://github.com/ldionne/metabench/blob/master/README.md

under the **Usage** title, but with just 1 dataset:

  metabench_add_dataset(dataset1 dataset1.cpp.erb "(0..30).step(10).to_a")

where dataset1.cpp.erb was the same as hana.map.cpp.erb in directory:

  https://github.com/ldionne/metabench/tree/master/benchmark/hetero/find_if

Then did cmake and then `make chart`:

--{--cut here--
make chart
Scanning dependencies of target chart
[ 50%] Generating dataset1.json
==> 25% (0.0s) dataset1.cpp.erb (n = 0)
(erb):25:in `render': undefined method `times' for nil:NilClass (NoMethodError)
	from /usr/lib/ruby/2.3.0/erb.rb:864:in `eval'
	from /usr/lib/ruby/2.3.0/erb.rb:864:in `result'
	from /home/evansl/prog_dev/github/cppljevans/composite_storage/benchmark/build/_metabench/metabench.rb:61:in `render'
	from /home/evansl/prog_dev/github/cppljevans/composite_storage/benchmark/build/_metabench/metabench.rb:87:in `block in measure'
	from /home/evansl/prog_dev/github/cppljevans/composite_storage/benchmark/build/_metabench/metabench.rb:82:in `each'
	from /home/evansl/prog_dev/github/cppljevans/composite_storage/benchmark/build/_metabench/metabench.rb:82:in `each_with_index'
	from /home/evansl/prog_dev/github/cppljevans/composite_storage/benchmark/build/_metabench/metabench.rb:82:in `measure'
	from -e:7:in `<main>'
CMakeFiles/chart.dir/build.make:64: recipe for target 'dataset1.json' failed
make[3]: *** [dataset1.json] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/chart.dir/all' failed
make[2]: *** [CMakeFiles/chart.dir/all] Error 2
CMakeFiles/Makefile2:74: recipe for target 'CMakeFiles/chart.dir/rule' failed
make[1]: *** [CMakeFiles/chart.dir/rule] Error 2
Makefile:118: recipe for target 'chart' failed
make: *** [chart] Error 2

Compilation exited abnormally with code 2 at Fri May 25 13:47:26
--}--cut here--

Please, what am I doing wrong?

2018-05-25.1500 CST.

Instead of the more complicated .cpp.erb, used the simple tuple example from:

https://github.com/ldionne/metabench/blob/master/README.md

IOW with dataset1.cpp.erb =
--{--cut here--
#include <tuple>

int main() {
#if defined(METABENCH)
    auto tuple = std::make_tuple(<%= (1..n).to_a.join(', ') %>);
#endif    
}
--}--cut here--

All works as expected.  I guess the hana.map.cpp.erb code had some preprocessing
done before it was finally used in the benchmark.

**Comment by ldionne** [comment]
`hana.map.cpp.erb` requires an `ENV` to be passed to it, as such:

```cmake
cmake_minimum_required(VERSION 3.10)

# Make sure Metabench can be found when writing include(metabench)
list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/../metabench")

# Actually include the module
include(metabench)

# Add new datasets
metabench_add_dataset(dataset1 dataset1.cpp.erb "(0..30).step(10).to_a" ENV "{k: 10}")
#                                                                       ^^^^^^^^^^^^^ THIS

# Add a new chart
metabench_add_chart(chart DATASETS dataset1)
```

I also slightly improved the error message produced when an error occurs while we're trying to generate the ERB template (in https://github.com/ldionne/metabench/commit/2f97ac9017ce73d26eadcd1fb93eb392cb615bb7).
