### ISSUE TITLE
Kvasir broke the build

### ISSUE THREAD

**Issue by ldionne** [ldionne/metabench#190]
Ping @odinthenerd 

https://travis-ci.org/ldionne/metabench/jobs/383907055#L4642
https://travis-ci.org/ldionne/metabench/jobs/383907059#L4662

Those are with slightly older compilers, i.e. Clang 3.6 and Clang 3.7. Perhaps you guys are not testing on those anymore?

**Comment by brunocodutra** [comment]
On that note, what do you think about bumping compiler versions a couple releases ahead, say GCC 5-8 and Clang 4-6?

**Comment by odinthenerd** [comment]
hmm looks like it Clang 3.5, 3.6 and 3.7 passed in our test suite, plus the last merge was 2 months ago... I'll have a look tomorrow, busy day today.

**Comment by ldionne** [comment]
@odinthenerd I'm redoing the build [here](https://travis-ci.org/ldionne/metabench/builds/384034482). Don't spend any time on this unless this one breaks again (I'll notify you).

@brunocodutra I am trying to add Clang 5 [here](https://travis-ci.org/ldionne/metabench/builds/385494558). I don't know whether Clang 6 and GCC 8 are supported on Travis -- please send a link my way if you find someone else doing it.

**Comment by brunocodutra** [comment]
I've been able to get Clang up to v6 and GCC up to v8 working [here](https://github.com/brunocodutra/alloy/blob/master/.travis.yml).

**Comment by odinthenerd** [comment]
in my latest PR I just removed kvasir support for 3.6 and 3.7. Those compilers do really really weird arity tests for aliases which are brittle in really weird ways. boost.tmp can work around this using arity tracking and some slow downs but I think I'm just dropping support for these in kvasir for now.

**Comment by ldionne** [comment]
Fixed by #195
