### ISSUE TITLE
benchmarks for map ignore making map

### ISSUE THREAD

**Issue by cppljevans** [ldionne/metabench#191]
The .erb file:

https://github.com/ldionne/metabench/blob/master/benchmark/hetero/find_if/hana.map.cpp.erb

ignores the compile time for creating the map.  I assume the rationale is that creation is done
1 time but finding is, most probably done, many times.  However, that might not always be
the case; hence, the cost of creation should also be benchmarked.

The attached shows benchmark with and without creation.

![hana map benchmark screenshot-2018-5-26 screenshot](https://user-images.githubusercontent.com/544899/40577425-ffd98568-60ca-11e8-961f-a4db76af0785.png)

**Comment by ldionne** [comment]
Indeed, the reasoning is that creation is done just once. We want to isolate the actual cost of doing the `find`. If you want to see the cost of creating the map itself, we have benchmarks that only create maps.
