### ISSUE TITLE
`any` algorithm for mp11 is typo'd as `all`

### ISSUE THREAD

**Issue by Quincunx271** [ldionne/metabench#199]
In /benchmark/type/any/mp11.list.cpp.erb, instead of running `mp_any_of`, it's actually running `mp_all_of`: https://github.com/ldionne/metabench/blob/d932ddc984c32a7d0931a064c78d0216f614e00b/benchmark/type/any/mp11.list.cpp.erb#L21

**Comment by ldionne** [comment]
Thanks for the report.
