### ISSUE TITLE
Allow adding a benchmark to the ALL target

### ISSUE THREAD

**Issue by ldionne** [ldionne/metabench#26]
Right now, `metabench_add_benchmark` does not add the target it creates to the `ALL` builtin target. It does not make sense to _always_ add it, because benchmarks are often optional, but it should be possible to add it. That can be achieved by passing an additional `ALL` argument to `metabench_add_benchmark`.

**Comment by brunocodutra** [comment]
This is addressed by #21.

By default, datasets are excluded from ALL, whereas benchmarks are included to it, but the user is free to setup the target afterwards using `set_target_properties`.
