### ISSUE TITLE
Would it be useful to provide means for visualizing the benchmark data?

### ISSUE THREAD

**Issue by ldionne** [ldionne/metabench#3]
Right now, Metabench only allows you to gather the benchmark data into a JSON file. What you do with it is completely up to you. However, it's almost always useful to be able to visualize the data in the JSON file as a chart. Would it make sense for Metabench to also create an html file that shows the chart associated to a benchmark?

**Comment by brunocodutra** [comment]
Absolutely.

Nothing fancy, some charting tool and a dropdown menu should do the trick.

**Comment by ldionne** [comment]
What I'm thinking about is that Metabench could generate the JSON file in `path/to/benchmark/chart.json` instead of `path/to/benchmark.json`, and also generate a `path/to/benchmark/index.html` file that would show the chart for the associated JSON file. This way, one could simply open the browser at `path/to/benchmark` to visualize it.

**Comment by brunocodutra** [comment]
Even simpler I guess.

**Comment by ldionne** [comment]
If I understood your initial suggestion correctly, you were suggesting that Metabench provides some kind of `chart.html` file that could be used to visualize any benchmark. The thing is that it forces users to copy this `chart.html` file into their own project if they want to visualize the charts, which is not as simple as it could be.

**Comment by brunocodutra** [comment]
Sure, that's why I like your idea better, this way the whole `_metabench` could be pushed as is with the rest of the project's documentation.
