### ISSUE TITLE
Javascript error prevents visualizing charts

### ISSUE THREAD

**Issue by brunocodutra** [ldionne/metabench#31]
Charts aren't currently displayed due to a Javascript exception.

**Comment by ldionne** [comment]
Hmm, it slipped by because the CI still passed. It would be handy to have a way to check that the generated HTML makes sense in the unit testing. Do you have an idea how to achieve this?

**Comment by brunocodutra** [comment]
> Hmm, it slipped by because the CI still passed

Been there, done that.

> It would be handy to have a way to check that the generated HTML makes sense in the unit testing. Do you have an idea how to achieve this?

For metabench I think [all we need is a browser](https://docs.travis-ci.com/user/gui-and-headless-browsers/) that could tell us whether it was able to render the page or not.

**Comment by ldionne** [comment]
Ahh, looking at how they do it in Travis seems complicated. I'm not sure the benefits are worth the cost. I'll just try to be more disciplined and check the charts before I commit.
