### ISSUE TITLE
Allow creating charts to display executable size

### ISSUE THREAD

**Issue by ldionne** [ldionne/metabench#34]
Right now, we gather data for the compilation time and the executable size, but we only ever plot the compilation time. It would be nice to allow selecting which aspect is displayed on the chart. I see the following possible designs here:

1. The aspect being plotted is set "statically", i.e. it is set somewhere and the generated `chart.html` displays that and only that aspect. To set the aspect being plotted, we can either set it in the call to `metabench_add_benchmark` by means of `metabench_add_benchmark(name [COMPILATION_TIME|EXECUTABLE_SIZE] ...)`, or we can set it in the `chart.json` file.

2. The aspect being plotted is "dynamic", in the sense that the chart contains all the necessary data and allows switching between aspects using e.g. a tooltip.

I would personally tend towards (1), because it seems more useful to me.

**Comment by brunocodutra** [comment]
I'm ok with displaying only one aspect, but I'd be against controlling it via `metabench_add_benchmark` as CMake should be strictly responsible for configuring the benchmark itself.

**Comment by ldionne** [comment]
Ok, so that's something that should be setup in `chart.json`? And it would default to showing the compilation time?

Note that I was initially in favour of using `metabench_add_benchmark` to control this, but I understand your point. My motivation was strictly convenience; it would be handy to have a way to specify the aspect without having to create a separate `chart.json` file with perhaps only one thing in it (the aspect being plotted).

I think one "problem" might be the fact that I'm thinking about `metabench_add_benchmark` like a `metabench_add_chart`, i.e. in my view the "benchmark" is actually tied to the chart. That might be wrong, though.

**Comment by brunocodutra** [comment]
> Ok, so that's something that should be setup in chart.json? And it would default to showing the compilation time?

Yes, a new property `aspect: <time|size>` should be enough.

> I think one "problem" might be the fact that I'm thinking about metabench_add_benchmark like a metabench_add_chart, i.e. in my view the "benchmark" is actually tied to the chart. That might be wrong, though.

Interesting, I see it rather as `gather_benchmark_data_for([...] DATASETS [...])` whose main objective is to export data as a JSON file that should be easily read by external tools. For convenience it also provides a default tool for visualization which the user may set up via `chart.json`.

> My motivation was strictly convenience; it would be handy to have a way to specify the aspect without having to create a separate chart.json file with perhaps only one thing in it (the aspect being plotted)

Good point. Perhaps it wouldn't be a bad idea at all to have the target created by `metabench_add_benchmark` only produce the JSON file and then provide a `metabench_add_chart` which would create a target that outputs the HTML file given a benchmark, the title and subtitle of the chart, the aspect to display and so on.

**Comment by ldionne** [comment]
I have no strong opinion. In fact, I think we would need more usage experience before we can really know what's best. Have you started using Metabench to benchmark Metal?

**Comment by brunocodutra** [comment]
> Have you started using Metabench to benchmark Metal?

I plan to look into it this weekend.

**Comment by ldionne** [comment]
Ok, also see #35 which is related to this.
