### ISSUE TITLE
Consider adding a suite of metaprogramming benchmarks

### ISSUE THREAD

**Issue by ldionne** [ldionne/metabench#35]
The primary reason why we're writing this tool, I think, is because we all need some sort of benchmarking for our own metaprogramming library. Furthermore, we'll necessarily end up benchmarking our library against other people's libraries. This leads to a duplication of effort if we all do the same in our own sandbox.

Instead, what we could do is write a suite of benchmarks for many different libraries, once, and store these benchmarks in this repository (or another repository). These benchmarks would thus be centralized in a single place, and the duplication of effort would be avoided. A non-exhaustive list of libraries that might want to participate:

- [MPL](https://github.com/boostorg/mpl)
- [Fusion](https://github.com/boostorg/fusion)
- [Brigand](https://github.com/edouarda/brigand)
- [Hana](https://github.com/boostorg/hana)
- [Metal](https://github.com/brunocodutra/metal)
- [Meta](https://github.com/ericniebler/meta)

This is just an idea, I'm not sure whether it's a good one.

@brunocodutra @edouarda @ericniebler Is this something that would be useful to you?

**Comment by edouarda** [comment]
I think it's a great idea!

**Comment by ericniebler** [comment]
Peter Dimov has a couple of blog posts where he benchmarks some meta programs. We could build off of his work.

**Comment by ldionne** [comment]
Actually, Hana already has a ton of these benchmarks written in a way compatible with Metabench, so I would suggest we start from there if anything. See #36 for an example of how I see this. Basically to start off, what I would need would be for everyone to provide a FindXXX CMake module that can be used to fetch their library (I already have FindHana, FindBoost and FindMeta, but I need FindMetal and FindBrigand if those exist).

**Comment by brunocodutra** [comment]
Excellent way for us to bring our efforts together towards better
metaprogramming.

Metal already provides MetalConfig.cmake and MetalConfigVersion.cmake upon
installation, which enable the use of `find_package`. Basically you just
need to install Metal somewhere and tell CMake about it by adding the
installation path prefix to `CMAKE_PREFIX_PATH`, in case it is not a
default location that is.

**Comment by ldionne** [comment]
Ok, it seems like we'll go forward with this idea so I'll close this issue in favour of PR #36.
