### ISSUE TITLE
[Design] Charts vs benchmarks

### ISSUE THREAD

**Issue by ldionne** [ldionne/metabench#60]
Right now, we have `metabench_add_dataset` and `metabench_add_benchmark`. It was suggested in #58 that we might want to add `metabench_add_chart`. Let's use this thread for further discussion on this issue.

**Comment by brunocodutra** [comment]
I believe this has been addressed by #101.
It was decided that `metabench_add_benchmark` should be understood as semantically equivalent to adding a chart, thus a separate `metabench_add_chart` isn't required.

**Comment by ldionne** [comment]
Actually, I was thinking that we should change the name to `metabench_add_chart`. What do you think?

**Comment by brunocodutra** [comment]
> Actually, I was thinking that we should change the name to
metabench_add_chart. What do you think?

I think it would be better indeed
