### ISSUE TITLE
Improve the URLs of charts on gh-pages

### ISSUE THREAD

**Issue by ldionne** [ldionne/metabench#64]
Right now, the URLs of individual charts look awkward, something like `metabench/hetero/benchmark.hetero.at.html`. It would be better to have something like `metabench/hetero/at.html`, or even `metabench/hetero/at`.

**Comment by brunocodutra** [comment]
What happened to MPL and Fusion benchmarks?

**Comment by ldionne** [comment]
Oh, I just disabled Boost while I was testing. They should be back once the benchmarks are updated.
