### ISSUE TITLE
[gh-pages] Allow selecting which compiler is being used

### ISSUE THREAD

**Issue by ldionne** [ldionne/metabench#67]
We might want to allow the compiler to be set globally or for each chart.

**Comment by brunocodutra** [comment]
I'm working on a way to select it globally.
I don't think it would make much sense to select the compiler per chart, as it doesn't make much sense to compare different benchmarks for different compilers.

**Comment by ldionne** [comment]
Agreed.

**Comment by ldionne** [comment]
Fixed by #75 and #76.
