### ISSUE TITLE
[gh-pages] Show a list of minimized benchmarks and expand on click

### ISSUE THREAD

**Issue by ldionne** [ldionne/metabench#68]
When we'll have a lot of charts, it will become unwieldy to just display all the charts as we do currently. Instead, we could display a list of "minimized" charts showing only the titles. Then when one clicks on the title, the box expands to a full chart. Just an idea, another approach might be better.

**Comment by brunocodutra** [comment]
I'm working on displaying charts inside [collapsible panels](http://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_collapsible_panel&stacked=h)

**Comment by ldionne** [comment]
Fixed by #78.
