### ISSUE TITLE
Consider a new name with better search engine optimization

### ISSUE THREAD

**Issue by badair** [ldionne/metabench#70]
When I ran a Google search for "metabench", the top 3 results were download links for a homonymous pre-existing program. The 4th result was the profile of Github user @metabench.

Suggested names that appear to fare better in search queries:
metribench 
benchbuild
buildbencher
compilemark
buildperf
perfpile
metribuild
staticperf
compileperf

These aren't as catchy, though.

**Comment by ldionne** [comment]
I think our ranking might improve if this project gets more publicity. In all cases, this is a tool meant for core C++ library writers, and I'm not too concerned about it not showing up 1st in search results.

You _do_ have a valid point, but I'll still close this as I believe the annoyance of renaming stuff and moving the repository outweighs the benefits of (possibly) ranking higher.
