### ISSUE TITLE
[gh-pages] Provide benchmark data through some public API

### ISSUE THREAD

**Issue by brunocodutra** [ldionne/metabench#71]
Following on from #69, we should provide some public API that others could use load benchmark data dynamically into their projects, something in the lines of [GH's API](https://developer.github.com/v3/).

**Comment by ldionne** [comment]
I think just providing the JSON files at some documented URL would be enough. Also, I don't think we can do better with GitHub Pages. After all, it's meant to be a site web publishing service, not a full blown server.

**Comment by brunocodutra** [comment]
> I think just providing the JSON files at some documented URL would be enough.

Forgive my ignorance of web technologies, [I just realized](http://stackoverflow.com/questions/18923328/is-there-a-way-to-enable-cors-on-github-pages) one may dynamically load JSON files hosted on gh-pages using `$.getJSON`. That fits perfectly what I meant by "some public API", I just thought it wouldn't be as easy as simply serving JSON files at some URL.

**Comment by ldionne** [comment]
No problem.
