### ISSUE TITLE
Move away from Highcharts

### ISSUE THREAD

**Issue by ldionne** [ldionne/metabench#9]
Highcharts' license is not compatible with open source licenses, so we'll have to move away from them.

**Comment by brunocodutra** [comment]
It seems like [Chart.js](https://github.com/nnnick/Chart.js) and [nvd3](https://github.com/novus/nvd3) would be good alternatives.

**Comment by brunocodutra** [comment]
Closing in favor of #13.

**Comment by brunocodutra** [comment]
This should be closed in favor of #13 .
